title: rodentrabies
description: >-
  Bitcoin, Lisp, software, economics...
  bc1qjnlky63epenkuaqes6n28s0zzywyg2q80u28vg
baseurl: ""
url: "https://rodentrabies.com"

plugins:
  - jekyll-feed

author:
  name: rodentrabies
  email: "rodentrabies@protonmail.com"

remote_theme: "jekyll/minima@1fe0fbf"

minima:
  nav_pages:
    - projects.md
    - about.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/rodentrabies"
    - title: X
      icon: x-twitter
      url: "https://x.com/rodentrabies"
